### ISSUE TITLE
How to check device id

### ISSUE THREAD

**Issue by peizhengfu** [SunHaixin0324/CMS50E_PPG_loader#1]
![屏幕截图 2024-03-10 185911](https://github.com/SunHaixin0324/CMS50E_PPG_loader/assets/50606839/2aba7f53-36b2-429c-8980-ed148c994068)

**Comment by SunHaixin0324** [comment]
The 4 characters after VEN_ is the VENDOR ID, and the other 4 characters after DEV_ is the PRODUCT ID. Remember to use hexadecimal notation.
