### ISSUE TITLE
There is a difference between the recorded heart rate and the real-time heart rate displayed on the device

### ISSUE THREAD

**Issue by scnu2631** [SunHaixin0324/CMS50E_PPG_loader#2]
Hello,

I've noticed a discrepancy while running your script to collect data for 30 seconds. On the device's accompanying software, my heart rate fluctuates in real-time, changing from 64 to 65 for 3 seconds, then to 66 for 3 seconds, and then back to 64. However, in the recorded CSV file, the heart rate remains constant at 64. Could you help me understand why there is a difference between the recorded heart rate and the real-time heart rate displayed on the device?

Thank you

**Comment by SunHaixin0324** [comment]
I also found similar problems in the process of use. Sometimes the serial port data could not receive real-time heart rate and blood oxygen data, but the PPG signal received was accurate, and I was not clear about the specific reasons.

**Comment by SunHaixin0324** [comment]
> Hello,
> 
> I've noticed a discrepancy while running your script to collect data for 30 seconds. On the device's accompanying software, my heart rate fluctuates in real-time, changing from 64 to 65 for 3 seconds, then to 66 for 3 seconds, and then back to 64. However, in the recorded CSV file, the heart rate remains constant at 64. Could you help me understand why there is a difference between the recorded heart rate and the real-time heart rate displayed on the device?
> 
> Thank you

I also found similar problems in the process of use. Sometimes the serial port data could not receive real-time heart rate and blood oxygen data, but the PPG signal received was accurate, and I was not clear about the specific reasons.
